import Head from "next/head";
import { GiProgression } from "react-icons/gi";
import placeholder from "../images/placeholder-image.png";
import Image from "next/image";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>Hypertrophy APP</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-zinc-100 p-4 text-center font-mono text-3xl text-zinc-950">
        <p className="text-red-600">Hypertrophy</p>
        <p>made easy</p>
      </div>
      <div className="bg-zinc-950 p-4 text-center font-mono text-2xl text-zinc-100">
        <p>
          ENDLESS <span className="text-red-600">PROGRESS</span>
        </p>
        <p className="whitespace-nowrap text-sm">
          No more <strong>guesswork</strong>. No more
          <strong>spreadsheets</strong>
        </p>
      </div>
      <main className="bg-zinc flex min-h-screen flex-col items-center p-4 font-mono">
        <div className="grid grid-cols-2 gap-2">
          <div>
            <GiProgression className="text-4xl" />
            <p className="text-2xl">
              Adaptive <span className="text-red-600">progress</span>
            </p>
            <p>
              The Hypertrophy App automatically adjusts your training based on
              your unique feedback around soreness, pump, and workload.
            </p>
          </div>
          <div>
            <Image src={placeholder} alt="placeholder" />
          </div>
        </div>
        <div className="grid grid-cols-2 gap-2">
          <div>
            <Image src={placeholder} alt="placeholder" />
          </div>
          <div>
            <GiProgression className="text-4xl" />
            <p className="text-2xl">
              Adaptive <span className="text-red-600">progress</span>
            </p>
            <p>
              The Hypertrophy App automatically adjusts your training based on
              your unique feedback around soreness, pump, and workload.
            </p>
          </div>
          <div>
            <GiProgression className="text-4xl" />
            <p className="text-2xl">
              Adaptive <span className="text-red-600">progress</span>
            </p>
            <p>
              The Hypertrophy App automatically adjusts your training based on
              your unique feedback around soreness, pump, and workload.
            </p>
          </div>
          <div>
            <Image src={placeholder} alt="placeholder" />
          </div>
        </div>
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
      </main>
      <footer className="bg-zinc-950 p-2 text-center font-mono text-sm text-zinc-100">
        This website serves solely as a portfolio project and does not have any
        commercial intent.
      </footer>
    </>
  );
}
